[/Script/EngineSettings.GameMapsSettings]
; After first Editor session: create Content/Maps/StartupMap.umap, then set:
; GameDefaultMap=/Game/Maps/StartupMap.StartupMap
; EditorStartupMap=/Game/Maps/StartupMap.StartupMap
GlobalDefaultGameMode=/Script/GTAWorld.GTAWorldGameMode

[/Script/Engine.RendererSettings]
r.DefaultFeature.AntiAliasing=2
r.GenerateMeshDistanceFields=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
